version: '3'
services:
  web:
    container_name: laravel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/laravel
    ports:
      - 3000:80
    depends_on:
      - phpmyadmin
  mysql:
    image: mysql:5.7.42
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 'mysql'
      PMA_PORT: '3306'
      MYSQL_ROOT_PASSWORD: 'root' # Use the same root password as in the MySQL container
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
